app/models.py
from . import db,login_manager
from datetime import datetime
from flask_login import UserMixin,current_user
from werkzeug.security import generate_password_hash,check_password_hash

class User(db.Model,UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255),unique = True,nullable = False)
    email  = db.Column(db.String(255),unique = True,nullable = False)
    secure_password = db.Column(db.String(255),nullable = False)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitches = db.relationship('Pitch', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='user', lazy='dynamic')
    upvote = db.relationship('Upvote',backref='user',lazy='dynamic')

    @property
    def set_password(self):
        raise AttributeError('u cannot read the password attribute')

    @set_password.setter
    def password(self, password):
        self.secure_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.secure_password,password) 

    
    def save_u(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}' 

class Pitch(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255),nullable = False)
    post = db.Column(db.Text(), nullable = False)
    comment = db.relationship('Comment',backref='pitch',lazy='dynamic')
    upvote = db.relationship('Upvote',backref='pitch',lazy='dynamic')
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    time = db.Column(db.DateTime, default = datetime.utcnow)
    category = db.Column(db.String(255), index = True,nullable=False)

    def save_p(self):
        db.session.add(self)
        db.session.commit()


    def __repr__(self):
        return f'Pitch {self.post}'

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.Text(),nullable = False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'),nullable = False)

    def save_p(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch_id):
        comments = Comment.query.filter_by(pitch_id=pitch_id).all()

        return comments

    def __repr__(self):
        return f'comment:{self.comment}'

class Upvote(db.Model):
    __tablename__ = 'upvotes'

    id = db.Column(db.Integer,primary_key=True)
    upvote = db.Column(db.Integer,default=1)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))


    def save(self):
        db.session.add(self)
        db.session.commit()

    def add_upvotes(cls,id):
        upvote_pitch = Upvote(user = current_user, pitch_id=id)
        upvote_pitch.save()

    @classmethod
    def get_upvotes(cls,id):
        upvote = Upvote.query.filter_by(pitch_id=id).all()
        return upvote

    @classmethod
    def all_upvotes(cls,pitch_id):
        upvotes = Upvote.query.order_by('id').all()
        return upvotes

    def __repr__(self):
        return f'{self.user_id}:{self.pitch_id}'






@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
from flask import Flask 
from config import config_options
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
# from flask_uploads import IMAGES, UploadSet,configure_uploads

db = SQLAlchemy()
bootstap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.load_view = 'auth.login'
# photos = UploadSet('photos',IMAGES)


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    login_manager.init_app(app)
    db.init_app(app)
    bootstap.init_app(app)
    from .auth import auth as auth_blueprint
    from .main import main as main_blueprint

    app.register_blueprint(auth_blueprint)
    app.register_blueprint(main_blueprint)

    

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint("main",__name__)
from .views import *

app/main/views.py
from flask import render_template, redirect, url_for,abort,request
from . import main
from flask_login import login_required,current_user
from ..models import User,Pitch,Comment,Upvote
from .form import UpdateProfile,UpvoteForm,PitchForm,CommentForm
from .. import db

@main.route('/')
def index():
    pitches = Pitch.query.all()
    job = Pitch.query.filter_by(category = 'Job').all() 
    event = Pitch.query.filter_by(category = 'Events').all()
    advertisement = Pitch.query.filter_by(category = 'Advertisement').all()
    return render_template('index.html', job = job,event = event, pitches = pitches,advertisement= advertisement)

@main.route('/create_new', methods = ['POST','GET'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        post = form.post.data
        category = form.category.data
        user_id = current_user
        new_pitch_object = Pitch(post=post,user_id=current_user._get_current_object().id,category=category,title=title)
        new_pitch_object.save_p()
        return redirect(url_for('main.index'))
    return render_template('create_pitch.html', form = form)

@main.route('/comment/<int:pitch_id>', methods = ['POST','GET'])
@login_required
def comment(pitch_id):
    form = CommentForm()
    pitch = Pitch.query.get(pitch_id)
    all_comments = Comment.query.filter_by(pitch_id = pitch_id).all()
    if form.validate_on_submit():
        comment = form.comment.data 
        pitch_id = pitch_id
        user_id = current_user._get_current_object().id
        new_comment = Comment(comment = comment,user_id = user_id,pitch_id = pitch_id)

        new_comment.save_c()
        return redirect(url_for('.comment', pitch_id = pitch_id))
    return render_template('comment.html', form =form, pitch = pitch,all_comments=all_comments)


@main.route('/user/<name>')
def profile(name):
    user = User.query.filter_by(username = name).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<name>/updateprofile', methods = ['POST','GET'])
@login_required
def updateprofile(name):
    form = UpdateProfile()
    user = User.query.filter_by(username = name).first()
    if user == None:
        abort(404)
    if form.validate_on_submit():
        user.bio = form.bio.data
        user.save_u()
        return redirect(url_for('.profile',name = name))
    return render_template('profile/update.html',form =form)


@main.route('/user/<name>/update/pic',methods= ['POST'])
@login_required
def update_pic(name):
    user = User.query.filter_by(username = name).first()
    if 'photo' in request.files:
        # filename = photos.save(request.files['photo'])
        # path = f'photos/{filename}'
        # user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',name=name))

@main.route('/like/<int:id>',methods = ['POST','GET'])
@login_required
def like(id):
    user = Upvote.query.get(id)
    users = User.filter_by(id = id).first()
    if users is None:
        return redirect(url_for('auth.login',user = user))
    all_upvotes = Upvote.query.filter_by(id=id).all()
    pitch = Pitch.query.get(id)
    new_vote = Upvote(user = user, pitch = pitch,upvote = 1)
    new_vote.save()
    return redirect(url_for('main.index',id = pitch.id))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pitch</title>
    {% block styles %}

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
    {% endblock %}
</head>

<body style="background-image:url(https://media.istockphoto.com/photos/night-sky-with-stars-and-clouds-picture-id532378051?b=1&k=20&m=532378051&s=170667a&w=0&h=K-6-sbYMHOM7i7yqFFdI0VCmFOY03rLAQMHxHObJUGY=)">
    <div class="overlay">
            {% block navbar %}
            {% include "navbar.html" %}
            {% endblock %}
            {% block content %}
            {% endblock %}
    </div>
{% block scripts %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/js/mdb.min.js"></script>
{% endblock %}
</body>
</html>

app/templates/comments.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="row">

            {% if all_comments %}
                <div class="col-md-7">
                    {% for comment in all_comments %}
                       <div class="card w-90 mb-3">
                           <div class="card-body">
                            <h5>{{comment.pitch.title}}</h5>
                             <p class="card-title">{{ comment.comment }}</p>
                             <p class="card-text">--- {{comment.user.username}}</p>
                           </div>
                       </div>
                    {% endfor %}
                   </div>
                   <div class="col-md-5">
                       {{wtf.quick_form(form)}}
                   </div>
               </div>
            {%else%}
            <div class="card w-90 mb-3">
                <div class="card-body">
                  <p class="card-title">no comments yet for this post. be the 1'st to comment</p>
                </div>
            </div> 
            <div class="col-md-5">
                
            </div>
                    {{wtf.quick_form(form)}}
                </div>
            {%endif%}
    </div>

{% endblock%}

app/templates/create_pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="row">
            {{wtf.quick_form(form)}}
        </div>
    </div>

{% endblock%}

app/templates/index.html
{% extends 'base.html'%}

{% block content %}
    <h2 class="text-center" id="all">All Pitches</h2>
    <div class="container">
        <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#all">All Pitches</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#jobs">Job Pitches</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#event">Event Pitches</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#ads">Advert Pitches</a>
            </li>
        </ul>
        <div class="tab-content">
            <div  class="container tab-pane active" id="pitches"><br>
                macro.display(pitches)
            </div>
            <div  class="container tab-pane fade" id="event"><br>
                macro.display(event)
            </div>
            <div  class="container tab-pane fade" id="jobs"><br>
                macro.display(job)
            </div>
            <div  class="container tab-pane fade" id="ads"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        macro.display(advertisement)
            </div>
        </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    </div>
{% endblock%}

app/templates/macros.html
{% macro display(piches) %}
<div class="row">
	{% if piches %}
		{% for category in piches %}
		<div class="col-md-4">
			<div class="thumbnail text-center">
			    <h5 class="card-header">{{category.title}}</h5>
			    <div class="card-body">
			    	<blockquote class="blockquote">
			    		<h2>{{category.post}}</h2>
            <footer class="blockquote-footer"> Posted by: {{category.user.username}}</footer>
            <p class="text-center"> Category: {{category.category}}</p>
			    	        </blockquote>
                            <p><span style="border-radius:50%;">{{category.comment.count()}} comments</span> 
                                
                                <span> <a href="{{url_for('main.like',id = category.id)}}"><i class="fa fa-thumbs-up" style="font-size:18px;color: green"></i></a> {{category.upvote.count()}}</span>
						&nbsp;

						<span><i class="fa fa-thumbs-down" style="color:red;"></i></span></p>
			    	<a href="{{url_for('main.comment',pitch_id = category.id)}}" class="btn btn-info btn-sm"> comment</a>
			        </div>
            </div>
            <hr>
        </div>

		{% endfor %}
	{% else %}
    <div class="card w-90 mb-3">
		<div class="card-body">

			<p class="card-title">0 posts on category</p>
		</div>
	</div>
	{% endif %}
</div>
{% endmacro %} 

app/templates/navbar.html
<nav class="mb-1 navbar navbar-expand-lg navbar-dark info-color">
    <a class="navbar-brand" href="{{url_for('main.index')}}"><strong>Pich-Site</strong> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse"  id="navbarSupportedContent-4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.index')}}">all pitches</a>
            </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.new_pitch')}}">new pitch</a>
                </li>
                {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" style= 'margin-right:30px' data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user"></i>&nbsp;<strong>{{current_user.username}}</strong> </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                  <a class="dropdown-item" href="{{url_for('main.profile',name=current_user.username)}}"><i class="far fa-user"></i>&nbsp; My account</a>
                  <a class="dropdown-item" href="{{url_for('auth.logout')}}"><i class="fas fa-sign-out-alt"></i>&nbsp; Log out</a>
                </div>
                </li>
            {% else %}
            <li class="nav-item">
                <a style= 'margin-right:30px' class="nav-link" href="{{url_for('auth.login')}}"><i class="fas fa-sign-in-alt"></i>&nbsp; <strong>Log in</strong></a>
            </li>
            {%endif%}

        </ul>
    </div>
</nav>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-md-4">
        <div class="card testimonial-card">
            <div class="purple-gradient color-block mb-3"></div>
            <div class="avatar mx-auto white">
                    {% if user.profile_pic_path %}
                    <img src="{{url_for('static',filename=user.profile_pic_path)}}" class=" card-img-top img-thumbnail" alt="woman avatar" style="height: 380px">
    
                    <!-- <img src="" alt="" class="img-thumbnail"> -->
    
                    {%else%}
                    <p>No profile pic</p>
    
                    {% endif %}  
            </div>
            <div class="card-body">
                <h4 class="card-title text-center"> {{user.username| capitalize}}</h4>
                <hr>
                {% if user.bio %}
                    <p><i class="fas fa-quote-left"></i> {{user.bio}}</p>
                {%else%}
                <p> {{user.username| capitalize}} no bio </p>
                {% endif %}
                {% if user == current_user %}
                <a href="{{url_for('main.updateprofile',name=user.username)}}">Edit profile</a>
                {% endif %}
            </div>
        </div>
  </div>

  <div class="col-md-4">
    <h3> </h3>


</div>
<div class="col-md-4">
    <div class="col-md-4">


                {% if user == current_user %}
            <form  action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype = "multipart/form-data">

              <input type="file"  name="photo" class="form-control" required>
              <input type="submit">
            </form>
              {% endif %}
          </div>

  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>
{% endblock %} 